spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}